-- 아고라 케피털 : 아고라 시장
-- Supabase SQL Editor에서 전체 실행하세요.
-- 회원의 계좌(PIN 확인)를 기준으로 상품 등록/좋아요/장바구니/구매를 처리합니다.

create table if not exists public.market_items (
  id uuid primary key default gen_random_uuid(),
  seller_account_id uuid not null references public.bank_accounts(id) on delete cascade,
  title text not null,
  description text not null,
  category text not null default '기타',
  price bigint not null check (price >= 0),
  preview_url text not null default '',
  download_url text not null default '',
  created_at timestamptz not null default now(),
  active boolean not null default true
);

create table if not exists public.market_likes (
  item_id uuid not null references public.market_items(id) on delete cascade,
  account_id uuid not null references public.bank_accounts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(item_id,account_id)
);

create table if not exists public.market_cart (
  item_id uuid not null references public.market_items(id) on delete cascade,
  account_id uuid not null references public.bank_accounts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(item_id,account_id)
);

create table if not exists public.market_purchases (
  id bigint generated by default as identity primary key,
  item_id uuid not null references public.market_items(id) on delete restrict,
  buyer_account_id uuid not null references public.bank_accounts(id) on delete restrict,
  seller_account_id uuid not null references public.bank_accounts(id) on delete restrict,
  price bigint not null check(price >= 0),
  created_at timestamptz not null default now()
);

create index if not exists market_items_category_idx
  on public.market_items(category,created_at desc);
create index if not exists market_purchases_buyer_idx
  on public.market_purchases(buyer_account_id,created_at desc);

alter table public.market_items enable row level security;
alter table public.market_likes enable row level security;
alter table public.market_cart enable row level security;
alter table public.market_purchases enable row level security;

revoke all on table public.market_items from anon, authenticated;
revoke all on table public.market_likes from anon, authenticated;
revoke all on table public.market_cart from anon, authenticated;
revoke all on table public.market_purchases from anon, authenticated;

create or replace function public.market_browse(p_category text default 'all', p_no text default '', p_pin text default '')
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  return jsonb_build_object(
    'items',
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id',m.id,
          'title',m.title,
          'description',m.description,
          'category',m.category,
          'price',m.price,
          'preview_url',m.preview_url,
          'download_url',m.download_url,
          'seller_name',a.name,
          'like_count',(select count(*) from public.market_likes l where l.item_id=m.id),
          'liked',exists(select 1 from public.market_likes l2 where l2.item_id=m.id and l2.account_id=(select id from public.bank_accounts where account_no=p_no and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex') limit 1))
        )
        order by m.created_at desc
      )
      from public.market_items m
      join public.bank_accounts a on a.id=m.seller_account_id
      where m.active=true
        and (p_category='all' or m.category=p_category)
    ),'[]'::jsonb)
  );
end;
$$;

create or replace function public.market_toggle_like(
  p_no text,p_pin text,p_item_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare a public.bank_accounts;
declare exists_like boolean;
begin
  select * into a
  from public.bank_accounts
  where account_no=p_no
    and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');

  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  if not exists(select 1 from public.market_items where id=p_item_id and active=true)
    then raise exception '상품을 찾을 수 없습니다.';
  end if;

  select exists(
    select 1 from public.market_likes
    where item_id=p_item_id and account_id=a.id
  ) into exists_like;

  if exists_like then
    delete from public.market_likes where item_id=p_item_id and account_id=a.id;
  else
    insert into public.market_likes(item_id,account_id) values(p_item_id,a.id);
  end if;

  return jsonb_build_object('liked',not exists_like);
end;
$$;

create or replace function public.market_cart_add(
  p_no text,p_pin text,p_item_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare a public.bank_accounts;
declare seller uuid;
begin
  select * into a from public.bank_accounts
  where account_no=p_no
    and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  select seller_account_id into seller
  from public.market_items
  where id=p_item_id and active=true;

  if seller is null then raise exception '상품을 찾을 수 없습니다.'; end if;
  if seller=a.id then raise exception '자신의 상품은 구매할 수 없습니다.'; end if;

  insert into public.market_cart(item_id,account_id)
  values(p_item_id,a.id)
  on conflict(item_id,account_id) do nothing;

  return true;
end;
$$;

create or replace function public.market_cart_remove(
  p_no text,p_pin text,p_item_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare a public.bank_accounts;
begin
  select * into a from public.bank_accounts
  where account_no=p_no
    and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  delete from public.market_cart
  where item_id=p_item_id and account_id=a.id;
  return true;
end;
$$;

create or replace function public.market_cart_list(
  p_no text,p_pin text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare a public.bank_accounts;
begin
  select * into a from public.bank_accounts
  where account_no=p_no
    and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  return jsonb_build_object(
    'items',coalesce((
      select jsonb_agg(jsonb_build_object(
        'item_id',m.id,
        'title',m.title,
        'price',m.price,
        'seller_name',s.name
      ) order by c.created_at desc)
      from public.market_cart c
      join public.market_items m on m.id=c.item_id
      join public.bank_accounts s on s.id=m.seller_account_id
      where c.account_id=a.id and m.active=true
    ),'[]'::jsonb)
  );
end;
$$;

create or replace function public.market_create_item(
  p_no text,p_pin text,p_title text,p_description text,
  p_category text,p_price bigint,p_preview_url text,p_download_url text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare a public.bank_accounts;
declare item public.market_items;
begin
  select * into a from public.bank_accounts
  where account_no=p_no
    and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  if p_title is null or length(trim(p_title))=0 then raise exception '상품 이름을 입력하세요.'; end if;
  if p_description is null or length(trim(p_description))=0 then raise exception '상품 설명을 입력하세요.'; end if;
  if p_price is null or p_price<0 then raise exception '가격을 확인하세요.'; end if;

  insert into public.market_items(
    seller_account_id,title,description,category,price,preview_url,download_url
  ) values(
    a.id,trim(p_title),trim(p_description),coalesce(nullif(trim(p_category),''),'기타'),
    p_price,coalesce(trim(p_preview_url),''),coalesce(trim(p_download_url),'')
  )
  returning * into item;

  return jsonb_build_object('id',item.id,'title',item.title,'price',item.price);
end;
$$;

create or replace function public.market_purchase_item(
  p_no text,p_pin text,p_item_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare buyer public.bank_accounts;
declare seller public.bank_accounts;
declare item public.market_items;
begin
  select * into buyer from public.bank_accounts
  where account_no=p_no
    and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex')
  for update;
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  select * into item from public.market_items
  where id=p_item_id and active=true
  for update;
  if not found then raise exception '상품을 찾을 수 없습니다.'; end if;

  if item.seller_account_id=buyer.id then
    raise exception '자신의 상품은 구매할 수 없습니다.';
  end if;

  if exists(
    select 1 from public.market_purchases
    where item_id=item.id and buyer_account_id=buyer.id
  ) then
    raise exception '이미 구매한 상품입니다.';
  end if;

  select * into seller
  from public.bank_accounts
  where id=item.seller_account_id
  for update;

  if buyer.balance<item.price then raise exception '잔액이 부족합니다.'; end if;

  update public.bank_accounts set balance=balance-item.price where id=buyer.id;
  update public.bank_accounts set balance=balance+item.price where id=seller.id;

  insert into public.market_purchases(
    item_id,buyer_account_id,seller_account_id,price
  ) values(item.id,buyer.id,seller.id,item.price);

  delete from public.market_cart
  where item_id=item.id and account_id=buyer.id;

  return jsonb_build_object(
    'item_id',item.id,
    'price',item.price,
    'download_url',item.download_url,
    'buyer_balance',buyer.balance-item.price
  );
end;
$$;

create or replace function public.market_purchase_cart(
  p_no text,p_pin text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare buyer public.bank_accounts;
declare c record;
declare total bigint:=0;
begin
  select * into buyer from public.bank_accounts
  where account_no=p_no
    and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex')
  for update;
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  for c in
    select m.id,m.seller_account_id,m.price
    from public.market_cart x
    join public.market_items m on m.id=x.item_id
    where x.account_id=buyer.id and m.active=true
    order by x.created_at
  loop
    if c.seller_account_id=buyer.id then continue; end if;
    if exists(select 1 from public.market_purchases where item_id=c.id and buyer_account_id=buyer.id) then continue; end if;
    total:=total+c.price;
  end loop;

  if buyer.balance<total then raise exception '장바구니 전체 금액보다 잔액이 부족합니다.'; end if;

  for c in
    select m.id,m.seller_account_id,m.price
    from public.market_cart x
    join public.market_items m on m.id=x.item_id
    where x.account_id=buyer.id and m.active=true
    order by x.created_at
  loop
    if c.seller_account_id=buyer.id then continue; end if;
    if exists(select 1 from public.market_purchases where item_id=c.id and buyer_account_id=buyer.id) then continue; end if;

    update public.bank_accounts set balance=balance-c.price where id=buyer.id;
    update public.bank_accounts set balance=balance+c.price where id=c.seller_account_id;

    insert into public.market_purchases(item_id,buyer_account_id,seller_account_id,price)
    values(c.id,buyer.id,c.seller_account_id,c.price);

    delete from public.market_cart where item_id=c.id and account_id=buyer.id;
  end loop;

  return jsonb_build_object('total',total,'balance',buyer.balance-total);
end;
$$;

revoke execute on function public.market_browse(text,text,text) from public,authenticated;
revoke execute on function public.market_toggle_like(text,text,uuid) from public,authenticated;
revoke execute on function public.market_cart_add(text,text,uuid) from public,authenticated;
revoke execute on function public.market_cart_remove(text,text,uuid) from public,authenticated;
revoke execute on function public.market_cart_list(text,text) from public,authenticated;
revoke execute on function public.market_create_item(text,text,text,text,text,bigint,text,text) from public,authenticated;
revoke execute on function public.market_purchase_item(text,text,uuid) from public,authenticated;
revoke execute on function public.market_purchase_cart(text,text) from public,authenticated;

grant execute on function public.market_browse(text,text,text) to anon;
grant execute on function public.market_toggle_like(text,text,uuid) to anon;
grant execute on function public.market_cart_add(text,text,uuid) to anon;
grant execute on function public.market_cart_remove(text,text,uuid) to anon;
grant execute on function public.market_cart_list(text,text) to anon;
grant execute on function public.market_create_item(text,text,text,text,text,bigint,text,text) to anon;
grant execute on function public.market_purchase_item(text,text,uuid) to anon;
grant execute on function public.market_purchase_cart(text,text) to anon;

grant usage on schema public to anon;


-- 실제 상품 파일 업로드용 Supabase Storage
-- 브라우저에서 파일을 직접 올리고 공개 다운로드 URL을 상품에 저장합니다.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values (
  'market-files',
  'market-files',
  true,
  10485760,
  array[
    'image/*',
    'application/pdf',
    'application/zip',
    'text/plain',
    'text/html',
    'text/css',
    'text/javascript',
    'application/javascript',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation'
  ]::text[]
)
on conflict (id) do update set
  public = true,
  file_size_limit = 10485760,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "market files public read" on storage.objects;
drop policy if exists "market files anon upload" on storage.objects;

create policy "market files public read"
on storage.objects
for select
to anon
using (bucket_id = 'market-files');

create policy "market files anon upload"
on storage.objects
for insert
to anon
with check (bucket_id = 'market-files');

notify pgrst,'reload schema';


-- 아고라 시장 가게 시스템
create table if not exists public.market_shops (
  id uuid primary key default gen_random_uuid(),
  owner_account_id uuid not null unique references public.bank_accounts(id) on delete cascade,
  name text not null,
  description text not null default '',
  created_at timestamptz not null default now(),
  active boolean not null default true
);
create index if not exists market_shops_owner_idx on public.market_shops(owner_account_id);
alter table public.market_shops enable row level security;
revoke all on table public.market_shops from anon, authenticated;

create or replace function public.market_my_shop(p_no text,p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare a public.bank_accounts;
declare sh public.market_shops;
begin
  select * into a from public.bank_accounts
  where account_no=p_no
    and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  select * into sh from public.market_shops
  where owner_account_id=a.id and active=true;

  if not found then
    return jsonb_build_object('shop',null);
  end if;

  return jsonb_build_object(
    'shop',jsonb_build_object(
      'id',sh.id,
      'name',sh.name,
      'description',sh.description,
      'created_at',to_char(sh.created_at at time zone 'Asia/Seoul','YYYY-MM-DD HH24:MI:SS')
    )
  );
end;
$$;

create or replace function public.market_create_shop(
  p_no text,p_pin text,p_name text,p_description text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare a public.bank_accounts;
declare sh public.market_shops;
declare setup_cost bigint:=1000;
begin
  select * into a from public.bank_accounts
  where account_no=p_no
    and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex')
  for update;
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  if exists(select 1 from public.market_shops where owner_account_id=a.id and active=true)
    then raise exception '이미 가게를 가지고 있습니다.'; end if;

  if p_name is null or length(trim(p_name))=0
    then raise exception '가게 이름을 입력하세요.'; end if;

  if length(trim(p_name))>40 then raise exception '가게 이름은 40자 이하로 입력하세요.'; end if;
  if length(coalesce(trim(p_description),''))>120 then raise exception '가게 소개는 120자 이하로 입력하세요.'; end if;

  if a.balance < setup_cost then
    raise exception '가게 설립 비용 1,000공이 필요합니다.';
  end if;

  update public.bank_accounts
  set balance=balance-setup_cost
  where id=a.id;

  insert into public.bank_transactions(account_id,type,amount)
  values(a.id,'withdraw',setup_cost);

  insert into public.market_shops(owner_account_id,name,description)
  values(a.id,trim(p_name),coalesce(trim(p_description),'')) returning * into sh;

  return jsonb_build_object(
    'shop',jsonb_build_object('id',sh.id,'name',sh.name,'description',sh.description),
    'balance',a.balance-setup_cost
  );
end;
$$;

-- 상품 등록은 이제 반드시 자신의 가게가 있어야 가능
create or replace function public.market_create_item(
  p_no text,p_pin text,p_title text,p_description text,
  p_category text,p_price bigint,p_preview_url text,p_download_url text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare a public.bank_accounts;
declare item public.market_items;
begin
  select * into a from public.bank_accounts
  where account_no=p_no
    and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  if not exists(select 1 from public.market_shops where owner_account_id=a.id and active=true)
    then raise exception '먼저 가게를 세워야 상품을 등록할 수 있습니다.'; end if;

  if p_title is null or length(trim(p_title))=0 then raise exception '상품 이름을 입력하세요.'; end if;
  if p_description is null or length(trim(p_description))=0 then raise exception '상품 설명을 입력하세요.'; end if;
  if p_price is null or p_price<0 then raise exception '가격을 확인하세요.'; end if;

  insert into public.market_items(
    seller_account_id,title,description,category,price,preview_url,download_url
  ) values(
    a.id,trim(p_title),trim(p_description),coalesce(nullif(trim(p_category),''),'기타'),
    p_price,coalesce(trim(p_preview_url),''),coalesce(trim(p_download_url),'')
  )
  returning * into item;

  return jsonb_build_object('id',item.id,'title',item.title,'price',item.price);
end;
$$;

-- 시장 목록에 가게 이름도 함께 표시
create or replace function public.market_browse(
  p_category text default 'all',
  p_no text default '',
  p_pin text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  return jsonb_build_object(
    'items',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',m.id,
        'title',m.title,
        'description',m.description,
        'category',m.category,
        'price',m.price,
        'preview_url',m.preview_url,
        'download_url',m.download_url,
        'seller_name',a.name,
        'shop_name',coalesce(sh.name,''),
        'like_count',(select count(*) from public.market_likes l where l.item_id=m.id),
        'liked',exists(
          select 1 from public.market_likes l2
          where l2.item_id=m.id
            and l2.account_id=(
              select id from public.bank_accounts
              where account_no=p_no
                and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex')
              limit 1
            )
        )
      )
      from public.market_items m
      join public.bank_accounts a on a.id=m.seller_account_id
      left join public.market_shops sh on sh.owner_account_id=a.id and sh.active=true
      where m.active=true
        and (p_category='all' or m.category=p_category)
      order by m.created_at desc
    )),'[]'::jsonb)
  );
end;
$;

revoke execute on function public.market_my_shop(text,text) from public,authenticated;
revoke execute on function public.market_create_shop(text,text,text,text) from public,authenticated;
revoke execute on function public.market_create_item(text,text,text,text,text,bigint,text,text) from public,authenticated;
revoke execute on function public.market_browse(text,text,text) from public,authenticated;

grant execute on function public.market_my_shop(text,text) to anon;
grant execute on function public.market_create_shop(text,text,text,text) to anon;
grant execute on function public.market_create_item(text,text,text,text,text,bigint,text,text) to anon;
grant execute on function public.market_browse(text,text,text) to anon;

grant usage on schema public to anon;
notify pgrst,'reload schema';
