-- 아고라 알림센터
create table if not exists public.agora_notifications (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.bank_accounts(id) on delete cascade,
  type text not null default 'system',
  title text not null,
  body text not null default '',
  link text not null default 'home',
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists agora_notifications_account_idx
  on public.agora_notifications(account_id,created_at desc);

alter table public.agora_notifications enable row level security;
revoke all on table public.agora_notifications from anon,authenticated;

create or replace function public.agora_notify(
  p_account_id uuid,p_type text,p_title text,p_body text,p_link text default 'home'
)
returns void language plpgsql security definer set search_path=''
as $$
begin
  if p_account_id is null then return; end if;
  insert into public.agora_notifications(account_id,type,title,body,link)
  values(p_account_id,coalesce(p_type,'system'),coalesce(p_title,'아고라 알림'),coalesce(p_body,''),coalesce(p_link,'home'));
end;
$$;

create or replace function public.notify_mail_insert()
returns trigger language plpgsql security definer set search_path=''
as $$
declare s public.bank_accounts;
begin
  select * into s from public.bank_accounts where id=new.sender_account_id;
  perform public.agora_notify(new.recipient_account_id,'mail','새 메일이 도착했습니다.',coalesce(s.name,'회원')||'님이 "'||new.subject||'" 메일을 보냈습니다.','mail');
  return new;
end;
$$;

drop trigger if exists agora_notify_mail on public.agora_mail;
create trigger agora_notify_mail after insert on public.agora_mail
for each row execute function public.notify_mail_insert();

create or replace function public.notify_transfer_insert()
returns trigger language plpgsql security definer set search_path=''
as $$
declare s public.bank_accounts;
begin
  select * into s from public.bank_accounts where id=new.sender_account_id;
  perform public.agora_notify(new.receiver_account_id,'transfer','송금 요청이 도착했습니다.',coalesce(s.name,'회원')||'님이 '||new.amount||'공 송금을 보냈습니다. 받아주세요.','student');
  return new;
end;
$$;

drop trigger if exists agora_notify_transfer on public.bank_transfers;
create trigger agora_notify_transfer after insert on public.bank_transfers
for each row execute function public.notify_transfer_insert();

create or replace function public.notify_transfer_update()
returns trigger language plpgsql security definer set search_path=''
as $$
declare r public.bank_accounts;
declare s public.bank_accounts;
begin
  if old.status=new.status then return new; end if;
  select * into r from public.bank_accounts where id=new.receiver_account_id;
  select * into s from public.bank_accounts where id=new.sender_account_id;
  if new.status='accepted' then
    perform public.agora_notify(new.sender_account_id,'transfer','송금이 수락되었습니다.',coalesce(r.name,'회원')||'님이 '||new.amount||'공 송금을 받았습니다.','student');
  elsif new.status='rejected' then
    perform public.agora_notify(new.sender_account_id,'transfer','송금이 거절되었습니다.',coalesce(r.name,'회원')||'님이 송금을 거절하여 '||new.amount||'공이 반환되었습니다.','student');
  end if;
  return new;
end;
$$;

drop trigger if exists agora_notify_transfer_update on public.bank_transfers;
create trigger agora_notify_transfer_update after update on public.bank_transfers
for each row execute function public.notify_transfer_update();

create or replace function public.notify_market_purchase()
returns trigger language plpgsql security definer set search_path=''
as $$
declare b public.bank_accounts;
declare item public.market_items;
begin
  select * into b from public.bank_accounts where id=new.buyer_account_id;
  select * into item from public.market_items where id=new.item_id;
  perform public.agora_notify(new.seller_account_id,'market','상품이 판매되었습니다.',coalesce(b.name,'회원')||'님이 "'||coalesce(item.title,'상품')||'"을 '||new.price||'공에 구매했습니다.','market');
  perform public.agora_notify(new.buyer_account_id,'market','상품 구매가 완료되었습니다.','"'||coalesce(item.title,'상품')||'"을 '||new.price||'공에 구매했습니다.','market');
  return new;
end;
$$;

drop trigger if exists agora_notify_market_purchase on public.market_purchases;
create trigger agora_notify_market_purchase after insert on public.market_purchases
for each row execute function public.notify_market_purchase();

create or replace function public.notify_loan_insert()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  perform public.agora_notify(new.account_id,'loan','대출 신청이 접수되었습니다.',new.amount||'공 대출 신청이 관리자 심사를 기다리고 있습니다.','student');
  return new;
end;
$$;

drop trigger if exists agora_notify_loan on public.bank_loans;
create trigger agora_notify_loan after insert on public.bank_loans
for each row execute function public.notify_loan_insert();

create or replace function public.notify_loan_update()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  if old.status=new.status then return new; end if;
  if new.status='approved' then
    perform public.agora_notify(new.account_id,'loan','대출이 승인되었습니다.',new.amount||'공이 계좌에 입금되었습니다.','student');
  elsif new.status='rejected' then
    perform public.agora_notify(new.account_id,'loan','대출이 거절되었습니다.',new.amount||'공 대출 신청이 거절되었습니다.','student');
  elsif new.status='paid' then
    perform public.agora_notify(new.account_id,'loan','대출 상환이 완료되었습니다.','대출을 모두 상환했습니다.','student');
  end if;
  return new;
end;
$$;

drop trigger if exists agora_notify_loan_update on public.bank_loans;
create trigger agora_notify_loan_update after update on public.bank_loans
for each row execute function public.notify_loan_update();

create or replace function public.notify_stock_trade()
returns trigger language plpgsql security definer set search_path=''
as $$
declare s public.agora_stocks;
begin
  select * into s from public.agora_stocks where id=new.stock_id;
  perform public.agora_notify(new.account_id,'stock','주식 거래가 완료되었습니다.',case when new.side='buy' then '매수' else '매도' end||' '||new.shares||'주 · '||new.total||'공 · '||coalesce(s.name,'주식'),'stock');
  return new;
end;
$$;

drop trigger if exists agora_notify_stock_trade on public.agora_stock_trades;
create trigger agora_notify_stock_trade after insert on public.agora_stock_trades
for each row execute function public.notify_stock_trade();

drop function if exists public.notification_list(text,text);
create or replace function public.notification_list(p_no text,p_pin text)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare a public.bank_accounts;
begin
 select * into a from public.bank_accounts where account_no=p_no and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
 if not found then raise exception '본인확인에 실패했습니다.'; end if;
 return jsonb_build_object(
  'notifications',coalesce((
   select jsonb_agg(jsonb_build_object(
    'id',n.id,'type',n.type,'title',n.title,'body',n.body,'link',n.link,
    'read_at',n.read_at,'date',to_char(n.created_at at time zone 'Asia/Seoul','YYYY-MM-DD HH24:MI')
   ) order by n.created_at desc)
   from public.agora_notifications n where n.account_id=a.id
  ),'[]'::jsonb)
 );
end;
$$;

drop function if exists public.notification_read(text,text,bigint);
create or replace function public.notification_read(p_no text,p_pin text,p_id bigint)
returns boolean language plpgsql security definer set search_path=''
as $$
declare a public.bank_accounts;
begin
 select * into a from public.bank_accounts where account_no=p_no and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
 if not found then raise exception '본인확인에 실패했습니다.'; end if;
 update public.agora_notifications set read_at=coalesce(read_at,now()) where id=p_id and account_id=a.id;
 return found;
end;
$$;

drop function if exists public.notification_read_all(text,text);
create or replace function public.notification_read_all(p_no text,p_pin text)
returns boolean language plpgsql security definer set search_path=''
as $$
declare a public.bank_accounts;
begin
 select * into a from public.bank_accounts where account_no=p_no and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
 if not found then raise exception '본인확인에 실패했습니다.'; end if;
 update public.agora_notifications set read_at=coalesce(read_at,now()) where account_id=a.id and read_at is null;
 return true;
end;
$$;

revoke execute on function public.agora_notify(uuid,text,text,text,text) from public,anon,authenticated;
revoke execute on function public.notification_list(text,text) from public,authenticated;
revoke execute on function public.notification_read(text,text,bigint) from public,authenticated;
revoke execute on function public.notification_read_all(text,text) from public,authenticated;
grant execute on function public.notification_list(text,text) to anon;
grant execute on function public.notification_read(text,text,bigint) to anon;
grant execute on function public.notification_read_all(text,text) to anon;
grant usage on schema public to anon;
notify pgrst,'reload schema';

-- 관리자 알림 발송
drop function if exists public.notification_admin_send_all(text,text,text,text,text,text);
create or replace function public.notification_admin_send_all(
  p_code text,p_type text,p_title text,p_body text,p_link text default 'home'
)
returns integer language plpgsql security definer set search_path=''
as $$
declare cnt integer;
begin
  if not public.bank_admin_login(p_code) then
    raise exception '관리자 코드가 올바르지 않습니다.';
  end if;
  if length(trim(coalesce(p_title,'')))=0 then raise exception '알림 제목을 입력하세요.'; end if;
  if length(trim(coalesce(p_body,'')))=0 then raise exception '알림 내용을 입력하세요.'; end if;
  if length(p_title)>100 or length(p_body)>1000 then raise exception '알림 제목은 100자, 내용은 1000자 이내입니다.'; end if;
  insert into public.agora_notifications(account_id,type,title,body,link)
  select id,coalesce(nullif(trim(p_type),''),'admin'),trim(p_title),trim(p_body),coalesce(nullif(trim(p_link),''),'home')
  from public.bank_accounts;
  get diagnostics cnt = row_count;
  return cnt;
end;
$$;

drop function if exists public.notification_admin_send_one(text,text,text,text,text,text);
create or replace function public.notification_admin_send_one(
  p_code text,p_no text,p_type text,p_title text,p_body text,p_link text default 'home'
)
returns boolean language plpgsql security definer set search_path=''
as $$
declare a public.bank_accounts;
begin
  if not public.bank_admin_login(p_code) then
    raise exception '관리자 코드가 올바르지 않습니다.';
  end if;
  select * into a from public.bank_accounts where account_no=trim(p_no);
  if not found then raise exception '해당 계좌를 찾을 수 없습니다.'; end if;
  if length(trim(coalesce(p_title,'')))=0 then raise exception '알림 제목을 입력하세요.'; end if;
  if length(trim(coalesce(p_body,'')))=0 then raise exception '알림 내용을 입력하세요.'; end if;
  if length(p_title)>100 or length(p_body)>1000 then raise exception '알림 제목은 100자, 내용은 1000자 이내입니다.'; end if;
  perform public.agora_notify(a.id,'admin',trim(p_title),trim(p_body),coalesce(nullif(trim(p_link),''),'home'));
  return true;
end;
$$;

revoke execute on function public.notification_admin_send_all(text,text,text,text,text,text) from public,authenticated;
revoke execute on function public.notification_admin_send_one(text,text,text,text,text,text) from public,authenticated;
grant execute on function public.notification_admin_send_all(text,text,text,text,text,text) to anon;
grant execute on function public.notification_admin_send_one(text,text,text,text,text,text) to anon;
notify pgrst,'reload schema';
