-- AGORA CAPITAL : 가상 주식 기능
-- Supabase SQL Editor에서 이 파일 전체를 1회 실행하세요.
-- 주식은 실제 금융상품이 아니라 학급용 가상경제 시스템입니다.

create table if not exists public.agora_stocks (
  id uuid primary key default gen_random_uuid(),
  symbol text not null unique,
  name text not null,
  description text not null default '',
  price bigint not null check (price > 0),
  previous_price bigint not null check (previous_price > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agora_stock_history (
  id bigint generated by default as identity primary key,
  stock_id uuid not null references public.agora_stocks(id) on delete cascade,
  price bigint not null check (price > 0),
  recorded_at timestamptz not null default now()
);

create table if not exists public.agora_stock_holdings (
  account_id uuid not null references public.bank_accounts(id) on delete cascade,
  stock_id uuid not null references public.agora_stocks(id) on delete cascade,
  shares bigint not null default 0 check (shares >= 0),
  avg_buy_price bigint not null default 0 check (avg_buy_price >= 0),
  primary key(account_id,stock_id)
);

create table if not exists public.agora_stock_trades (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.bank_accounts(id) on delete cascade,
  stock_id uuid not null references public.agora_stocks(id) on delete cascade,
  side text not null check (side in ('buy','sell')),
  shares bigint not null check (shares > 0),
  price bigint not null check (price > 0),
  total bigint not null check (total > 0),
  created_at timestamptz not null default now()
);

alter table public.agora_stocks enable row level security;
alter table public.agora_stock_history enable row level security;
alter table public.agora_stock_holdings enable row level security;
alter table public.agora_stock_trades enable row level security;

revoke all on table public.agora_stocks from anon, authenticated;
revoke all on table public.agora_stock_history from anon, authenticated;
revoke all on table public.agora_stock_holdings from anon, authenticated;
revoke all on table public.agora_stock_trades from anon, authenticated;

insert into public.agora_stocks(symbol,name,description,price,previous_price)
values
('AGR','아고라 홀딩스','아고라 케피털 가상경제의 대표 기업',1000,1000),
('RAIL','아고라 레일','철도·교통 분야 가상 기업',1500,1500),
('PIX','픽셀웍스','디자인·디지털 콘텐츠 가상 기업',800,800),
('BYTE','바이트랩','소프트웨어·도구 분야 가상 기업',1200,1200)
on conflict(symbol) do nothing;

insert into public.agora_stock_history(stock_id,price)
select id,price from public.agora_stocks s
where not exists (
  select 1 from public.agora_stock_history h where h.stock_id=s.id
);

drop function if exists public.stock_browse(text,text,text);
create or replace function public.stock_browse(p_no text default '', p_pin text default '')
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare a public.bank_accounts;
declare has_member boolean := false;
begin
  if coalesce(p_no,'')<>'' then
    select * into a from public.bank_accounts
    where account_no=p_no
      and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
    if not found then raise exception '주식 로그인에 실패했습니다.'; end if;
    has_member := true;
  end if;

  return jsonb_build_object(
    'stocks',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',s.id,'symbol',s.symbol,'name',s.name,'description',s.description,
        'price',s.price,'previous_price',s.previous_price,
        'change_percent',round(((s.price-s.previous_price)::numeric/nullif(s.previous_price,0))*100,2),
        'updated_at',s.updated_at,
        'history',coalesce((
          select jsonb_agg(hx.price order by hx.recorded_at asc)
          from (
            select h.price,h.recorded_at
            from public.agora_stock_history h
            where h.stock_id=s.id
            order by h.recorded_at desc
            limit 20
          ) hx
        ),'[]'::jsonb),
        'shares',case when has_member then coalesce((
          select h.shares from public.agora_stock_holdings h
          where h.account_id=a.id and h.stock_id=s.id
        ),0) else 0 end,
        'avg_buy_price',case when found and a.id is not null then coalesce((
          select h.avg_buy_price from public.agora_stock_holdings h
          where h.account_id=a.id and h.stock_id=s.id
        ),0) else 0 end
      ) order by s.symbol)
      from public.agora_stocks s where s.active
    ),'[]'::jsonb)
  );
end;
$$;

drop function if exists public.stock_buy(text,text,uuid,bigint);
create or replace function public.stock_buy(p_no text,p_pin text,p_stock_id uuid,p_shares bigint)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare a public.bank_accounts;
declare s public.agora_stocks;
declare h public.agora_stock_holdings;
declare total bigint;
declare new_avg bigint;
begin
  if p_shares is null or p_shares<1 then raise exception '매수 수량은 1주 이상이어야 합니다.'; end if;

  select * into a from public.bank_accounts
  where account_no=p_no and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex')
  for update;
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  select * into s from public.agora_stocks where id=p_stock_id and active for update;
  if not found then raise exception '주식을 찾을 수 없습니다.'; end if;

  total := s.price*p_shares;
  if a.balance<total then raise exception '잔액이 부족합니다.'; end if;

  select * into h from public.agora_stock_holdings
  where account_id=a.id and stock_id=s.id for update;

  if not found then
    insert into public.agora_stock_holdings(account_id,stock_id,shares,avg_buy_price)
    values(a.id,s.id,p_shares,s.price);
  else
    new_avg := ((h.shares*h.avg_buy_price)+(p_shares*s.price))/(h.shares+p_shares);
    update public.agora_stock_holdings
    set shares=h.shares+p_shares,avg_buy_price=new_avg
    where account_id=a.id and stock_id=s.id;
  end if;

  update public.bank_accounts set balance=balance-total where id=a.id;
  insert into public.bank_transactions(account_id,type,amount) values(a.id,'withdraw',total);
  insert into public.agora_stock_trades(account_id,stock_id,side,shares,price,total)
  values(a.id,s.id,'buy',p_shares,s.price,total);

  return jsonb_build_object('price',s.price,'shares',p_shares,'total',total,'balance',a.balance-total);
end;
$$;

drop function if exists public.stock_sell(text,text,uuid,bigint);
create or replace function public.stock_sell(p_no text,p_pin text,p_stock_id uuid,p_shares bigint)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare a public.bank_accounts;
declare s public.agora_stocks;
declare h public.agora_stock_holdings;
declare total bigint;
declare remain bigint;
begin
  if p_shares is null or p_shares<1 then raise exception '매도 수량은 1주 이상이어야 합니다.'; end if;

  select * into a from public.bank_accounts
  where account_no=p_no and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex')
  for update;
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  select * into s from public.agora_stocks where id=p_stock_id and active for update;
  if not found then raise exception '주식을 찾을 수 없습니다.'; end if;

  select * into h from public.agora_stock_holdings
  where account_id=a.id and stock_id=s.id for update;
  if not found or h.shares<p_shares then raise exception '보유 주식 수량이 부족합니다.'; end if;

  total := s.price*p_shares;
  remain := h.shares-p_shares;

  if remain=0 then
    delete from public.agora_stock_holdings where account_id=a.id and stock_id=s.id;
  else
    update public.agora_stock_holdings set shares=remain where account_id=a.id and stock_id=s.id;
  end if;

  update public.bank_accounts set balance=balance+total where id=a.id;
  insert into public.bank_transactions(account_id,type,amount) values(a.id,'deposit',total);
  insert into public.agora_stock_trades(account_id,stock_id,side,shares,price,total)
  values(a.id,s.id,'sell',p_shares,s.price,total);

  return jsonb_build_object('price',s.price,'shares',p_shares,'total',total,'balance',a.balance+total);
end;
$$;

drop function if exists public.stock_my_trades(text,text);
create or replace function public.stock_my_trades(p_no text,p_pin text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare a public.bank_accounts;
begin
  select * into a from public.bank_accounts
  where account_no=p_no and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  return jsonb_build_object(
    'trades',coalesce((
      select jsonb_agg(jsonb_build_object(
        'side',t.side,'symbol',s.symbol,'name',s.name,'shares',t.shares,
        'price',t.price,'total',t.total,
        'date',to_char(t.created_at at time zone 'Asia/Seoul','YYYY-MM-DD HH24:MI:SS')
      ) order by t.created_at desc)
      from public.agora_stock_trades t join public.agora_stocks s on s.id=t.stock_id
      where t.account_id=a.id
    ),'[]'::jsonb)
  );
end;
$$;

drop function if exists public.stock_admin_list(text);
create or replace function public.stock_admin_list(p_code text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
begin
  if not public.bank_admin_login(p_code) then raise exception '관리자 코드가 올바르지 않습니다.'; end if;
  return jsonb_build_object('stocks',coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',s.id,'symbol',s.symbol,'name',s.name,'price',s.price,'previous_price',s.previous_price,
      'change_percent',round(((s.price-s.previous_price)::numeric/nullif(s.previous_price,0))*100,2)
    ) order by s.symbol) from public.agora_stocks s
  ),'[]'::jsonb));
end;
$$;

drop function if exists public.stock_admin_change(text,uuid,numeric);
create or replace function public.stock_admin_change(p_code text,p_stock_id uuid,p_percent numeric)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare s public.agora_stocks;
declare new_price bigint;
begin
  if not public.bank_admin_login(p_code) then raise exception '관리자 코드가 올바르지 않습니다.'; end if;
  if p_percent is null or p_percent < -90 or p_percent > 500 then raise exception '등락률은 -90%%에서 500%% 사이입니다.'; end if;

  select * into s from public.agora_stocks where id=p_stock_id for update;
  if not found then raise exception '주식을 찾을 수 없습니다.'; end if;

  new_price := greatest(1,round(s.price*(1+p_percent/100.0))::bigint);

  update public.agora_stocks
  set previous_price=price,price=new_price,updated_at=now()
  where id=s.id;

  insert into public.agora_stock_history(stock_id,price) values(s.id,new_price);

  return jsonb_build_object('id',s.id,'price',new_price,'previous_price',s.price);
end;
$$;

revoke execute on function public.stock_browse(text,text) from public,authenticated;
revoke execute on function public.stock_buy(text,text,uuid,bigint) from public,authenticated;
revoke execute on function public.stock_sell(text,text,uuid,bigint) from public,authenticated;
revoke execute on function public.stock_my_trades(text,text) from public,authenticated;
revoke execute on function public.stock_admin_list(text) from public,authenticated;
revoke execute on function public.stock_admin_change(text,uuid,numeric) from public,authenticated;

grant execute on function public.stock_browse(text,text) to anon;
grant execute on function public.stock_buy(text,text,uuid,bigint) to anon;
grant execute on function public.stock_sell(text,text,uuid,bigint) to anon;
grant execute on function public.stock_my_trades(text,text) to anon;
grant execute on function public.stock_admin_list(text) to anon;
grant execute on function public.stock_admin_change(text,uuid,numeric) to anon;

grant usage on schema public to anon;
notify pgrst,'reload schema';
