-- AGORA CAPITAL : 가상 주식 기능
-- Supabase SQL Editor에서 이 파일 전체를 1회 실행하세요.
-- 주식은 실제 금융상품이 아니라 학급용 가상경제 시스템입니다.

create table if not exists public.agora_stocks (
  id uuid primary key default gen_random_uuid(),
  symbol text not null unique,
  name text not null,
  description text not null default '',
  price bigint not null check (price > 0),
  previous_price bigint not null check (previous_price > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agora_stock_history (
  id bigint generated by default as identity primary key,
  stock_id uuid not null references public.agora_stocks(id) on delete cascade,
  price bigint not null check (price > 0),
  recorded_at timestamptz not null default now()
);

create table if not exists public.agora_stock_holdings (
  account_id uuid not null references public.bank_accounts(id) on delete cascade,
  stock_id uuid not null references public.agora_stocks(id) on delete cascade,
  shares bigint not null default 0 check (shares >= 0),
  avg_buy_price bigint not null default 0 check (avg_buy_price >= 0),
  primary key(account_id,stock_id)
);

create table if not exists public.agora_stock_trades (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.bank_accounts(id) on delete cascade,
  stock_id uuid not null references public.agora_stocks(id) on delete cascade,
  side text not null check (side in ('buy','sell')),
  shares bigint not null check (shares > 0),
  price bigint not null check (price > 0),
  total bigint not null check (total > 0),
  created_at timestamptz not null default now()
);

alter table public.agora_stocks enable row level security;
alter table public.agora_stock_history enable row level security;
alter table public.agora_stock_holdings enable row level security;
alter table public.agora_stock_trades enable row level security;

revoke all on table public.agora_stocks from anon, authenticated;
revoke all on table public.agora_stock_history from anon, authenticated;
revoke all on table public.agora_stock_holdings from anon, authenticated;
revoke all on table public.agora_stock_trades from anon, authenticated;

-- 아고라 시장의 가게를 주식 종목으로 사용합니다.
-- 각 활성 가게마다 1개의 가상 주식이 만들어지며, 시작가는 1,000공입니다.
-- 실제 금융상품이 아니며 아고라 내부의 가상 화폐 "공"으로만 거래됩니다.

alter table public.agora_stocks add column if not exists shop_id uuid references public.market_shops(id) on delete cascade;
create unique index if not exists agora_stocks_shop_uidx on public.agora_stocks(shop_id) where shop_id is not null;
update public.agora_stocks set active=false,updated_at=now() where shop_id is null;

insert into public.agora_stocks(symbol,shop_id,name,description,price,previous_price,active)
select 'SHOP-'||left(replace(sh.id::text,'-',''),8),sh.id,sh.name,
       '아고라 시장의 "'||sh.name||'" 가게 주식',1000,1000,true
from public.market_shops sh
where sh.active=true and not exists(select 1 from public.agora_stocks s where s.shop_id=sh.id);

insert into public.agora_stock_history(stock_id,price)
select s.id,s.price from public.agora_stocks s
where s.active and not exists(select 1 from public.agora_stock_history h where h.stock_id=s.id);

drop function if exists public.stock_browse(text,text,text);
create or replace function public.stock_browse(p_no text default '',p_pin text default '')
returns jsonb language plpgsql security definer set search_path=''
as $$
declare a public.bank_accounts; declare has_member boolean:=false;
begin
  insert into public.agora_stocks(symbol,shop_id,name,description,price,previous_price,active)
  select 'SHOP-'||left(replace(sh.id::text,'-',''),8),sh.id,sh.name,
         '아고라 시장의 "'||sh.name||'" 가게 주식',1000,1000,true
  from public.market_shops sh where sh.active=true
    and not exists(select 1 from public.agora_stocks s where s.shop_id=sh.id);

  if coalesce(p_no,'')<>'' then
    select * into a from public.bank_accounts where account_no=p_no and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
    if not found then raise exception '주식 로그인에 실패했습니다.'; end if;
    has_member:=true;
  end if;

  return jsonb_build_object('stocks',coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',s.id,'symbol',s.symbol,'name',sh.name,
      'description','아고라 시장의 "'||sh.name||'" 가게 주식','shop_id',sh.id,
      'price',s.price,'previous_price',s.previous_price,
      'change_percent',round(((s.price-s.previous_price)::numeric/nullif(s.previous_price,0))*100,2),
      'updated_at',s.updated_at,
      'history',coalesce((select jsonb_agg(hx.price order by hx.recorded_at asc)
        from (select h.price,h.recorded_at from public.agora_stock_history h where h.stock_id=s.id order by h.recorded_at desc limit 20) hx),'[]'::jsonb),
      'shares',case when has_member then coalesce((select h.shares from public.agora_stock_holdings h where h.account_id=a.id and h.stock_id=s.id),0) else 0 end,
      'avg_buy_price',case when has_member then coalesce((select h.avg_buy_price from public.agora_stock_holdings h where h.account_id=a.id and h.stock_id=s.id),0) else 0 end
    ) order by sh.name)
    from public.agora_stocks s join public.market_shops sh on sh.id=s.shop_id and sh.active=true
    where s.active=true
  ),'[]'::jsonb));
end;
$$;

drop function if exists public.stock_buy(text,text,uuid,bigint);
create or replace function public.stock_buy(p_no text,p_pin text,p_stock_id uuid,p_shares bigint)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare a public.bank_accounts;
declare s public.agora_stocks;
declare h public.agora_stock_holdings;
declare total bigint;
declare new_avg bigint;
begin
  if p_shares is null or p_shares<1 then raise exception '매수 수량은 1주 이상이어야 합니다.'; end if;

  select * into a from public.bank_accounts
  where account_no=p_no and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex')
  for update;
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  select * into s from public.agora_stocks where id=p_stock_id and active for update;
  if not found then raise exception '주식을 찾을 수 없습니다.'; end if;

  total := s.price*p_shares;
  if a.balance<total then raise exception '잔액이 부족합니다.'; end if;

  select * into h from public.agora_stock_holdings
  where account_id=a.id and stock_id=s.id for update;

  if not found then
    insert into public.agora_stock_holdings(account_id,stock_id,shares,avg_buy_price)
    values(a.id,s.id,p_shares,s.price);
  else
    new_avg := ((h.shares*h.avg_buy_price)+(p_shares*s.price))/(h.shares+p_shares);
    update public.agora_stock_holdings
    set shares=h.shares+p_shares,avg_buy_price=new_avg
    where account_id=a.id and stock_id=s.id;
  end if;

  update public.bank_accounts set balance=balance-total where id=a.id;
  insert into public.bank_transactions(account_id,type,amount) values(a.id,'withdraw',total);
  insert into public.agora_stock_trades(account_id,stock_id,side,shares,price,total)
  values(a.id,s.id,'buy',p_shares,s.price,total);

  return jsonb_build_object('price',s.price,'shares',p_shares,'total',total,'balance',a.balance-total);
end;
$$;

drop function if exists public.stock_sell(text,text,uuid,bigint);
create or replace function public.stock_sell(p_no text,p_pin text,p_stock_id uuid,p_shares bigint)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare a public.bank_accounts;
declare s public.agora_stocks;
declare h public.agora_stock_holdings;
declare total bigint;
declare remain bigint;
begin
  if p_shares is null or p_shares<1 then raise exception '매도 수량은 1주 이상이어야 합니다.'; end if;

  select * into a from public.bank_accounts
  where account_no=p_no and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex')
  for update;
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  select * into s from public.agora_stocks where id=p_stock_id and active for update;
  if not found then raise exception '주식을 찾을 수 없습니다.'; end if;

  select * into h from public.agora_stock_holdings
  where account_id=a.id and stock_id=s.id for update;
  if not found or h.shares<p_shares then raise exception '보유 주식 수량이 부족합니다.'; end if;

  total := s.price*p_shares;
  remain := h.shares-p_shares;

  if remain=0 then
    delete from public.agora_stock_holdings where account_id=a.id and stock_id=s.id;
  else
    update public.agora_stock_holdings set shares=remain where account_id=a.id and stock_id=s.id;
  end if;

  update public.bank_accounts set balance=balance+total where id=a.id;
  insert into public.bank_transactions(account_id,type,amount) values(a.id,'deposit',total);
  insert into public.agora_stock_trades(account_id,stock_id,side,shares,price,total)
  values(a.id,s.id,'sell',p_shares,s.price,total);

  return jsonb_build_object('price',s.price,'shares',p_shares,'total',total,'balance',a.balance+total);
end;
$$;

drop function if exists public.stock_my_trades(text,text);
create or replace function public.stock_my_trades(p_no text,p_pin text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare a public.bank_accounts;
begin
  select * into a from public.bank_accounts
  where account_no=p_no and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex');
  if not found then raise exception '본인확인에 실패했습니다.'; end if;

  return jsonb_build_object(
    'trades',coalesce((
      select jsonb_agg(jsonb_build_object(
        'side',t.side,'symbol',s.symbol,'name',s.name,'shares',t.shares,
        'price',t.price,'total',t.total,
        'date',to_char(t.created_at at time zone 'Asia/Seoul','YYYY-MM-DD HH24:MI:SS')
      ) order by t.created_at desc)
      from public.agora_stock_trades t join public.agora_stocks s on s.id=t.stock_id
      where t.account_id=a.id
    ),'[]'::jsonb)
  );
end;
$$;

drop function if exists public.stock_admin_list(text);
create or replace function public.stock_admin_list(p_code text)
returns jsonb language plpgsql security definer set search_path=''
as $$
begin
  if not public.bank_admin_login(p_code) then raise exception '관리자 코드가 올바르지 않습니다.'; end if;
  return jsonb_build_object('stocks',coalesce((
    select jsonb_agg(jsonb_build_object('id',s.id,'symbol',s.symbol,'name',sh.name,'price',s.price,'previous_price',s.previous_price,
      'change_percent',round(((s.price-s.previous_price)::numeric/nullif(s.previous_price,0))*100,2)) order by sh.name)
    from public.agora_stocks s join public.market_shops sh on sh.id=s.shop_id and sh.active=true
    where s.active
  ),'[]'::jsonb));
end;
$$;

drop function if exists public.stock_admin_change(text,uuid,numeric);
create or replace function public.stock_admin_change(p_code text,p_stock_id uuid,p_percent numeric)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare s public.agora_stocks; declare new_price bigint;
begin
  if not public.bank_admin_login(p_code) then raise exception '관리자 코드가 올바르지 않습니다.'; end if;
  if p_percent is null or p_percent < -90 or p_percent > 500 then raise exception '등락률은 -90%%에서 500%% 사이입니다.'; end if;
  select st.* into s from public.agora_stocks st join public.market_shops sh on sh.id=st.shop_id and sh.active=true
  where st.id=p_stock_id for update;
  if not found then raise exception '활성화된 가게 주식을 찾을 수 없습니다.'; end if;
  new_price:=greatest(1,round(s.price*(1+p_percent/100.0))::bigint);
  update public.agora_stocks set previous_price=price,price=new_price,updated_at=now() where id=s.id;
  insert into public.agora_stock_history(stock_id,price) values(s.id,new_price);
  return jsonb_build_object('id',s.id,'price',new_price,'previous_price',s.price);
end;
$$;

revoke execute on function public.stock_browse(text,text) from public,authenticated;
revoke execute on function public.stock_buy(text,text,uuid,bigint) from public,authenticated;
revoke execute on function public.stock_sell(text,text,uuid,bigint) from public,authenticated;
revoke execute on function public.stock_my_trades(text,text) from public,authenticated;
revoke execute on function public.stock_admin_list(text) from public,authenticated;
revoke execute on function public.stock_admin_change(text,uuid,numeric) from public,authenticated;

grant execute on function public.stock_browse(text,text) to anon;
grant execute on function public.stock_buy(text,text,uuid,bigint) to anon;
grant execute on function public.stock_sell(text,text,uuid,bigint) to anon;
grant execute on function public.stock_my_trades(text,text) to anon;
grant execute on function public.stock_admin_list(text) to anon;
grant execute on function public.stock_admin_change(text,uuid,numeric) to anon;

grant usage on schema public to anon;
notify pgrst,'reload schema';

-- 시장 활동을 가게 주가에 자동 반영합니다.
create or replace function public.agora_shop_stock_activity(p_shop_id uuid,p_percent numeric)
returns void language plpgsql security definer set search_path=''
as $$
declare s public.agora_stocks; declare new_price bigint; declare bounded numeric;
begin
  bounded:=least(5,greatest(-5,p_percent));
  select * into s from public.agora_stocks where shop_id=p_shop_id and active=true for update;
  if not found then return; end if;
  new_price:=greatest(1,round(s.price*(1+bounded/100.0))::bigint);
  update public.agora_stocks set previous_price=price,price=new_price,updated_at=now() where id=s.id;
  insert into public.agora_stock_history(stock_id,price) values(s.id,new_price);
end;
$$;

create or replace function public.agora_shop_item_stock_trigger()
returns trigger language plpgsql security definer set search_path=''
as $$ begin perform public.agora_shop_stock_activity(new.shop_id,1); return new; end; $$;

create or replace function public.agora_shop_purchase_stock_trigger()
returns trigger language plpgsql security definer set search_path=''
as $$
declare shop_id uuid;
begin
  select m.shop_id into shop_id from public.market_items m where m.id=new.item_id;
  if shop_id is not null then perform public.agora_shop_stock_activity(shop_id,3); end if;
  return new;
end;
$$;

create or replace function public.agora_shop_like_stock_trigger()
returns trigger language plpgsql security definer set search_path=''
as $$
declare shop_id uuid;
begin
  select m.shop_id into shop_id from public.market_items m where m.id=coalesce(new.item_id,old.item_id);
  if shop_id is not null then perform public.agora_shop_stock_activity(shop_id,case when tg_op='INSERT' then 0.5 else -0.5 end); end if;
  if tg_op='DELETE' then return old; else return new; end if;
end;
$$;

drop trigger if exists agora_stock_on_item on public.market_items;
create trigger agora_stock_on_item after insert on public.market_items for each row execute function public.agora_shop_item_stock_trigger();
drop trigger if exists agora_stock_on_purchase on public.market_purchases;
create trigger agora_stock_on_purchase after insert on public.market_purchases for each row execute function public.agora_shop_purchase_stock_trigger();
drop trigger if exists agora_stock_on_like on public.market_likes;
create trigger agora_stock_on_like after insert or delete on public.market_likes for each row execute function public.agora_shop_like_stock_trigger();

grant usage on schema public to anon;
notify pgrst,'reload schema';
