-- 602은행 Supabase cloud database
-- Supabase Dashboard > SQL Editor에 전체를 붙여넣고 Run 하세요.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.bank_settings (
  key text primary key,
  value text not null
);

create table if not exists public.bank_accounts (
  id uuid primary key default gen_random_uuid(),
  account_no text not null unique,
  name text not null,
  pin_hash text not null,
  balance bigint not null default 0 check (balance >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.bank_transactions (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.bank_accounts(id) on delete cascade,
  type text not null check (type in ('deposit','withdraw')),
  amount bigint not null check (amount > 0),
  created_at timestamptz not null default now()
);

alter table public.bank_settings enable row level security;
alter table public.bank_accounts enable row level security;
alter table public.bank_transactions enable row level security;

revoke all on table public.bank_settings from anon, authenticated;
revoke all on table public.bank_accounts from anon, authenticated;
revoke all on table public.bank_transactions from anon, authenticated;

insert into public.bank_settings(key,value)
values ('admin_pin_hash', encode(extensions.digest('6020','sha256'),'hex'))
on conflict (key) do nothing;

-- 기존 602은행 데모 회원 3명 + 앞서 만든 무작위 16개 계좌/PIN.
-- 이미 같은 계좌번호가 있으면 건너뜁니다.
insert into public.bank_accounts(account_no,name,pin_hash,balance) values
('602-184','회원1',encode(extensions.digest('7391','sha256'),'hex'),1000),
('602-739','회원2',encode(extensions.digest('2846','sha256'),'hex'),1000),
('602-426','회원3',encode(extensions.digest('9153','sha256'),'hex'),1000),
('602-915','회원4',encode(extensions.digest('4628','sha256'),'hex'),1000),
('602-263','회원5',encode(extensions.digest('1375','sha256'),'hex'),1000),
('602-847','회원6',encode(extensions.digest('8064','sha256'),'hex'),1000),
('602-531','회원7',encode(extensions.digest('3519','sha256'),'hex'),1000),
('602-608','회원8',encode(extensions.digest('6247','sha256'),'hex'),1000),
('602-372','회원9',encode(extensions.digest('5982','sha256'),'hex'),1000),
('602-954','회원10',encode(extensions.digest('7436','sha256'),'hex'),1000),
('602-116','회원11',encode(extensions.digest('2168','sha256'),'hex'),1000),
('602-685','회원12',encode(extensions.digest('9705','sha256'),'hex'),1000),
('602-497','회원13',encode(extensions.digest('4831','sha256'),'hex'),1000),
('602-823','회원14',encode(extensions.digest('6529','sha256'),'hex'),1000),
('602-350','회원15',encode(extensions.digest('3087','sha256'),'hex'),1000),
('602-761','회원16',encode(extensions.digest('8412','sha256'),'hex'),1000)
on conflict (account_no) do nothing;

create or replace function public.bank_member_login(p_no text, p_name text, p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare a public.bank_accounts;
begin
  select * into a
  from public.bank_accounts
  where account_no = p_no
    and name = p_name
    and pin_hash = encode(extensions.digest(p_pin,'sha256'),'hex');

  if not found then
    raise exception '계좌번호, 이름 또는 고유번호가 올바르지 않습니다.';
  end if;

  return jsonb_build_object(
    'account', jsonb_build_object(
      'id', a.id, 'no', a.account_no, 'name', a.name, 'balance', a.balance
    ),
    'tx', coalesce((
      select jsonb_agg(jsonb_build_object(
        'type',t.type,'amount',t.amount,'date',to_char(t.created_at at time zone 'Asia/Seoul','YYYY-MM-DD HH24:MI:SS')
      ) order by t.created_at desc)
      from public.bank_transactions t where t.account_id=a.id
    ), '[]'::jsonb)
  );
end;
$$;

drop function if exists public.bank_transaction(text,text,text,bigint);

create or replace function public.bank_transaction(
  p_no text, p_pin text, p_type text, p_amount bigint, p_admin_code text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare a public.bank_accounts;
declare new_balance bigint;
begin
  if not public.bank_admin_login(p_admin_code) then
    raise exception '관리자 승인 코드가 올바르지 않습니다.';
  end if;

  if p_type not in ('deposit','withdraw') or p_amount < 1 then
    raise exception '잘못된 거래입니다.';
  end if;

  select * into a
  from public.bank_accounts
  where account_no=p_no
    and pin_hash=encode(extensions.digest(p_pin,'sha256'),'hex')
  for update;

  if not found then
    raise exception '본인확인에 실패했습니다.';
  end if;

  if p_type='withdraw' and a.balance < p_amount then
    raise exception '잔액이 부족합니다.';
  end if;

  new_balance := case when p_type='deposit' then a.balance+p_amount else a.balance-p_amount end;

  update public.bank_accounts set balance=new_balance where id=a.id;
  insert into public.bank_transactions(account_id,type,amount)
  values(a.id,p_type,p_amount);

  return jsonb_build_object(
    'account', jsonb_build_object('id',a.id,'no',a.account_no,'name',a.name,'balance',new_balance),
    'type',p_type,'amount',p_amount
  );
end;
$$;

create or replace function public.bank_admin_login(p_code text)
returns boolean
language sql
security definer
set search_path = ''
as $$
  select exists(
    select 1 from public.bank_settings
    where key='admin_pin_hash'
      and value=encode(extensions.digest(p_code,'sha256'),'hex')
  );
$$;

create or replace function public.bank_admin_list(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.bank_admin_login(p_code) then
    raise exception '관리자 코드가 올바르지 않습니다.';
  end if;

  return jsonb_build_object(
    'accounts', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',a.id,'no',a.account_no,'name',a.name,'balance',a.balance
      ) order by a.account_no)
      from public.bank_accounts a
    ), '[]'::jsonb),
    'transactions', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',t.id,'no',a.account_no,'name',a.name,'type',t.type,'amount',t.amount,
        'date',to_char(t.created_at at time zone 'Asia/Seoul','YYYY-MM-DD HH24:MI:SS')
      ) order by t.created_at desc)
      from public.bank_transactions t
      join public.bank_accounts a on a.id=t.account_id
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.bank_admin_add(
  p_code text, p_name text, p_no text, p_pin text, p_balance bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare a public.bank_accounts;
begin
  if not public.bank_admin_login(p_code) then
    raise exception '관리자 코드가 올바르지 않습니다.';
  end if;
  if p_name is null or length(trim(p_name))=0 then raise exception '이름을 입력하세요.'; end if;
  if p_no !~ '^602-[0-9]{3}$' then raise exception '계좌번호는 602-000 형식이어야 합니다.'; end if;
  if p_pin !~ '^[0-9]{4,8}$' then raise exception '고유번호는 4~8자리 숫자여야 합니다.'; end if;
  if p_balance is null or p_balance < 0 then raise exception '초기 잔액을 확인하세요.'; end if;
  if exists(select 1 from public.bank_accounts where account_no=p_no) then raise exception '이미 존재하는 계좌번호입니다.'; end if;

  insert into public.bank_accounts(account_no,name,pin_hash,balance)
  values(p_no,trim(p_name),encode(extensions.digest(p_pin,'sha256'),'hex'),p_balance)
  returning * into a;

  return jsonb_build_object('id',a.id,'no',a.account_no,'name',a.name,'balance',a.balance);
end;
$$;

create or replace function public.bank_admin_delete(p_code text, p_no text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.bank_admin_login(p_code) then
    raise exception '관리자 코드가 올바르지 않습니다.';
  end if;
  delete from public.bank_accounts where account_no=p_no;
  return found;
end;
$$;

revoke execute on function public.bank_member_login(text,text,text) from public, authenticated;
revoke execute on function public.bank_transaction(text,text,text,bigint) from public, anon, authenticated;
revoke execute on function public.bank_transaction(text,text,text,bigint,text) from public, authenticated;
revoke execute on function public.bank_admin_login(text) from public, authenticated;
revoke execute on function public.bank_admin_list(text) from public, authenticated;
revoke execute on function public.bank_admin_add(text,text,text,text,bigint) from public, authenticated;
revoke execute on function public.bank_admin_delete(text,text) from public, authenticated;

grant execute on function public.bank_member_login(text,text,text) to anon;
grant execute on function public.bank_transaction(text,text,text,bigint,text) to anon;
grant execute on function public.bank_admin_login(text) to anon;
grant execute on function public.bank_admin_list(text) to anon;
grant execute on function public.bank_admin_add(text,text,text,text,bigint) to anon;
grant execute on function public.bank_admin_delete(text,text) to anon;

-- PostgREST schema cache 새로고침
notify pgrst, 'reload schema';
